name: Release Pipeline and Artifact

on:
  release:
    types: [published]

jobs:
  pipeline-release:
    runs-on: ubuntu-latest
    env:
      MAX_PAGES: -1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run pipeline in Docker
        run: |
          chmod +x data-pipeline-docker.sh
          ./data-pipeline-docker.sh
      - name: Upload compressed ChromaDB artifact
        run: |
          gh release upload ${{ github.event.release.tag_name }} data/enmemoryalpha_db.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
